# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    file_manager:
        class: AppBundle\Utils\FileManager
        #arguments: ["%files_dir%"]
